### ISSUE TITLE
migrar projeto pra aspnet5 CoreCLR

### ISSUE THREAD

**Issue by luisrudge** [dotnetfloripa/site#3]
trocar nancy pelo projeto padrão aspnet 5 MVC + razor. Idealmente, acho legal fazer só com o CoreCLR pra rodar em todas as plataformas por padrão

**Comment by andrecarlucci** [comment]
Acho bem legal!

**Comment by andrecalil** [comment]
Ainda de pé? Posso assumir este.

**Comment by luisrudge** [comment]
Opa, eu tava esperando pra sair o beta8, mas adiaram uma semana (https://twitter.com/DamianEdwards/status/651119748487385089).

Mas você pode fazer! Só sugiro esperar até o lançamento do beta8 pra evitar retrabalho.

[roadmap](https://github.com/aspnet/Home/wiki/Roadmap#schedule)

**Comment by andrecalil** [comment]
Ok, vou começar mas aguardo para subir depois de atualizar. Existe alguma convenção para eu sinalizar que a issue foi assumida?

**Comment by luisrudge** [comment]
Só bota teu nome ali:

![image](https://cloud.githubusercontent.com/assets/941075/10297896/15ce0d3a-6baf-11e5-8420-017894253e98.png)

Se precisar de ajuda, é só avisar

**Comment by andrecalil** [comment]
@luisrudge os comandos aqui da issue não estão disponíveis pra mim. Se pá já pode encerra-la, não?
