### ISSUE TITLE
Testes para acesso a dados

### ISSUE THREAD

**Issue by andrecalil** [dotnetfloripa/site#6]
Penso que a próxima evolução do site seja incluir uma fonte de dados externa, certo? O que acham que criarmos uma camada de testes com a versão que temos agora, para garantir que próximos repositórios não quebrem o site?

**Comment by andrecarlucci** [comment]
Acho massa! Mas eu queria usar o mini-biggy pra validar o framework.

-----Original Message-----

**Comment by andrecalil** [comment]
Não vejo problema, mas uma coisa de cada vez, não? Primeiro montamos os testes com o "repositório" que existe hoje, daí partimos para um próximo repositório (usando o mini-biggy, se for o caso).

**Comment by luisrudge** [comment]
acho que não precisamos de testes ainda. por enquanto, o nosso repositório é somente leitura, então nem faz tanto sentido. Vamos migrar para o mini-biggy e pensar em testes quando formos criar a área de vagas.

O que acham?

**Comment by luisrudge** [comment]
Criei a issue pra migrar os dados: https://github.com/dotnetfloripa/site/issues/7

**Comment by andrecalil** [comment]
Eu acho que seria interessante, tanto para validar a leitura (afinal, será um refactoring) quanto para showcase (mais para isso, na verdade). De qualquer forma, sem objeções quanto a deixar para fazer depois.

**Comment by luisrudge** [comment]
Acho legal ter os testes também, mas os testes que fizermos agora, vão embora quando a gente migrar pro aspnet5 e mini-biggy. Só quero evitar o retrabalho
