### ISSUE TITLE
Fonte de dados externa

### ISSUE THREAD

**Issue by andrecalil** [dotnetfloripa/site#9]
Ei, vamos utilizar uma fonte de dados externa? Aquele repositório com tudo hardcoded é meio... feio. Vcs tem algo em mente? Pensei no DocumentDB.

**Comment by andrecalil** [comment]
hahahaha acabei de ver que sugeri a mesma coisa ano passado.
Podemos fazer esta issue junto da #7

**Comment by luisrudge** [comment]
cara.. só vale a pena ir pra fonte de dado externa quando a gente adicionar a parte de vagas.. sem isso, não tem porque.. Até porque, sem a parte de vagas, é melhor até redirecionar o domínio direto pro site do meetup e já tá bom.

**Comment by andrecalil** [comment]
@luisrudge @andrecarlucci resolvemos essa issue, se pá?
